"""Translate legacy Ollama requests to a local vLLM OpenAI API."""

from __future__ import annotations

import json
import os
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.request import Request, urlopen


VLLM_URL = os.environ.get("VLLM_URL", "http://vllm:8000/v1").rstrip("/")
# No hardcoded fallback. This previously defaulted to a literal published in
# this repo, so an unset secret left the gateway talking to vLLM with a known
# credential instead of failing. Raised at import so a misconfigured gateway
# refuses to start and says why in its container log, rather than serving
# requests that appear to work.
VLLM_API_KEY = (os.environ.get("VLLM_API_KEY") or "").strip()
if not VLLM_API_KEY:
    raise SystemExit(
        "llm-gateway: VLLM_API_KEY is unset. It is generated by "
        "deployment/setup-secrets.sh and passed in docker-compose.llm.yml."
    )
VLLM_MODEL = os.environ.get("VLLM_MODEL", "Qwen/Qwen3.8-27B-FP8")


class GatewayHandler(BaseHTTPRequestHandler):
    def _json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:
        if self.path == "/":
            self._json(200, {"status": "ok", "backend": "vllm"})
        else:
            self._json(404, {"error": "not found"})

    def do_POST(self) -> None:
        if self.path not in {"/api/chat", "/api/generate"}:
            self._json(404, {"error": "not found"})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length) or b"{}")
            if self.path == "/api/generate":
                messages = [{"role": "user", "content": str(payload.get("prompt") or "")}]
            else:
                messages = payload.get("messages") or []
            options = payload.get("options") or {}
            request_payload = {
                "model": VLLM_MODEL,
                "messages": messages,
                "stream": False,
                "temperature": options.get("temperature", 0.2),
                "response_format": {"type": "json_object"},
            }
            if options.get("num_predict"):
                request_payload["max_tokens"] = int(options["num_predict"])
            # Ollama's `think` has a vLLM equivalent, and dropping it is not harmless.
            # Qwen3 is a hybrid thinking model: left to think, it spends the whole
            # max_tokens budget on reasoning, never emits the answer, and vLLM returns
            # finish_reason "length" with content NULL. WF10 sends think:false for
            # exactly this reason and used to get clean JSON out of Ollama; once the
            # gateway swallowed the flag, its 1600-token budget bought 1600 tokens of
            # reasoning and 0 of output (measured 2026-09-03: null content at 1600
            # tokens with the flag dropped, valid JSON at 746 with it honoured).
            if payload.get("think") is False:
                request_payload["chat_template_kwargs"] = {"enable_thinking": False}
            request = Request(
                f"{VLLM_URL}/chat/completions",
                data=json.dumps(request_payload).encode("utf-8"),
                headers={
                    "Authorization": f"Bearer {VLLM_API_KEY}",
                    "Content-Type": "application/json",
                },
                method="POST",
            )
            with urlopen(request, timeout=600) as response:
                result = json.load(response)
            choices = result.get("choices") or []
            message = choices[0].get("message") if choices else {}
            # `or ""` rather than a .get default: vLLM sends the key present and set
            # to null when the model produced no answer text, so the default never
            # fires and callers get None where the Ollama API would never return it.
            content = (message.get("content") or "") if isinstance(message, dict) else ""
            if self.path == "/api/generate":
                self._json(200, {"response": content, "done": True})
            else:
                self._json(200, {"message": {"role": "assistant", "content": content}, "done": True})
        except Exception as exc:
            self._json(502, {"error": str(exc)})

    def log_message(self, _format: str, *_args: object) -> None:
        return


if __name__ == "__main__":
    ThreadingHTTPServer(("0.0.0.0", 8080), GatewayHandler).serve_forever()
