"""Small OpenAI-compatible/Ollama chat client used by n8n and upload parsing."""

from __future__ import annotations

import os
from typing import Any

import requests


def _vllm_api_key() -> str:
    """Return the vLLM bearer key, or fail loudly.

    This used to fall back to a hardcoded literal. That turned a missing secret
    into a request signed with a credential published in this repo: it would
    authenticate against a default-configured server, so the stack kept working
    while its LLM tier was protected by a known string. A dropped variable is
    exactly what moving secrets into an encrypted store is most likely to
    produce, so the unset case now names itself instead.
    """
    key = (os.environ.get("VLLM_API_KEY") or "").strip()
    if not key:
        raise RuntimeError(
            "VLLM_API_KEY is unset -- refusing to call the vLLM backend with a "
            "default credential. It is generated by deployment/setup-secrets.sh; "
            "if it is set in .env but missing here, check the Python runner's "
            "allowed-env list in deployment/n8n-task-runners.json."
        )
    return key


def chat_completion(
    messages: list[dict[str, str]],
    *,
    model: str | None = None,
    timeout: int = 120,
    backend: str | None = None,
) -> str:
    """Return assistant text while preserving the legacy Ollama option."""
    selected = (backend or os.environ.get("SPOTTER_LLM_BACKEND", "vllm")).strip().lower()
    selected_model = model or os.environ.get("SECURITY_LLM_MODEL", "Qwen/Qwen3.8-27B-FP8")
    if selected == "vllm":
        base_url = os.environ.get("VLLM_URL", "http://vllm:8000/v1").rstrip("/")
        headers = {
            "Authorization": f"Bearer {_vllm_api_key()}",
            "Content-Type": "application/json",
        }
        response = requests.post(
            f"{base_url}/chat/completions",
            headers=headers,
            json={
                "model": os.environ.get("VLLM_MODEL", selected_model),
                "messages": messages,
                "stream": False,
                "temperature": 0.2,
                "response_format": {"type": "json_object"},
            },
            timeout=timeout,
        )
        response.raise_for_status()
        choices = response.json().get("choices") or []
        message = choices[0].get("message") if choices and isinstance(choices[0], dict) else {}
        return message.get("content", "") if isinstance(message, dict) else ""

    # Legacy Ollama-shaped path. Ollama itself was removed from the stack on
    # 2026-09-04; what answers /api/chat now is llm-gateway, which translates to
    # vLLM and FORCES model=VLLM_MODEL, so `selected_model` is advisory here.
    # num_ctx is likewise inert -- the gateway rebuilds the request and forwards
    # only messages, temperature, num_predict and think.
    response = requests.post(
        f"{os.environ.get('OLLAMA_URL', 'http://llm-gateway:8080').rstrip('/')}/api/chat",
        json={
            "model": selected_model,
            "format": "json",
            "think": False,
            "messages": messages,
            "stream": False,
            "options": {"temperature": 0.2, "num_predict": 1600, "num_ctx": 8192},
        },
        timeout=timeout,
    )
    response.raise_for_status()
    payload: dict[str, Any] = response.json()
    return payload.get("message", {}).get("content", "")
